DOC add link to the hub with skops filter
skops-dev/skops pull request #129
Opened 2022-09-06 14:27 UTC by adrinjalali

Fixes #127 

cc @osanseviero @skops-dev/maintainers

2022-09-06 15:05 UTC, BenjaminBossan approved these changes
LGTM

We should probably address #114 soon to avoid showing so many CI-related repos.

2022-09-06 15:32 UTC, adrinjalali commented
CI finally green

2022-09-07 08:35 UTC, BenjaminBossan requested changes
Some links are broken. Maybe you can check if your editor has an RST mode with a command to add hyperlinks, since it's so easy to mess them up.

2022-09-07 08:35 UTC, BenjaminBossan commented on docs/hf_hub.rst
> +`here <https://huggingface.co/models?other=skops>`_`
```suggestion
`here <https://huggingface.co/models?other=skops>`_.
```

2022-09-07 10:48 UTC, adrinjalali commented
hehe, sometimes my editor puts two backticks when I type one, annoying.

2022-09-08 14:54 UTC, BenjaminBossan commented
@adrinjalali From my POV this can be merged but it needs to be updated.

2022-09-08 15:21 UTC, adrinjalali commented
@BenjaminBossan you need to change your "review" here for me to have the green button 😁

2022-09-08 15:36 UTC, BenjaminBossan approved these changes

2022-09-08 15:38 UTC, merged