fix isort / black conflict
skops-dev/skops pull request #189
Opened 2022-10-14 15:14 UTC by seanabreau

updates pre commit hook so that isort complies with black formatting standards, preventing potential issues

2022-10-14 15:47 UTC, BenjaminBossan commented
Thanks for this PR. I have just skimmed it but in general think the changes are good. I'm not sure how the other maintainers feel about some of them, e.g. the use of `suppress`, so I'd like to hear their opinion first.

The change regarding `_extracted_from_save_29` should probably be reverted: This is a hot part of the code that'll probably change 5 times in the next month or so.

And just something for the future: This kind of change is appreciated but please open an issue first and quickly describe your intent. This way we can ensure that there is no wasted effort.

2022-10-15 14:54 UTC, seanabreau commented
sounds good I've reverted `_extracted_from_save_29`

Ok sorry about that going forward I'll create and issue or address an existing issue :)

2022-10-17 09:32 UTC, adrinjalali requested changes
please revert the rest of the changes.

Generally, such a PR by a first time contributor is not appreciated. I'm okay with merging the few that I've commented on.

We're more than happy to have you as a contributor, but it's better to start by fixing existing issues rather than fixing code the way you think is better. Once you're a maintainer on the repo, then such changes can be welcome.

2022-10-17 09:32 UTC, adrinjalali commented on .pre-commit-config.yaml
> +        - --profile=black
this is somewhere else configured

2022-10-17 09:32 UTC, adrinjalali commented on skops/card/_model_card.py
> +            model_file = self.metadata.to_dict().get("model_file")
this change is fine

2022-10-17 09:32 UTC, adrinjalali commented on skops/card/_model_card.py
> +            metadata_repr = "\n".join(metadata_reprs)
I guess

2022-10-17 09:32 UTC, adrinjalali commented on skops/io/_numpy.py
> +        ) from e
nice!

2022-11-04 11:39 UTC, BenjaminBossan commented
@seanabreau Are you still working on this?

2022-11-29 15:35 UTC, adrinjalali commented
Closing due to inactivity.

2022-11-29 15:35 UTC, closed without merging