remove `trusted=True` from skops.io.load(s)
skops-dev/skops pull request #422
Opened 2024-06-06 11:58 UTC by adrinjalali

We got a CVE report where an attacker can execute arbitrary code with `trusted=True`. While one can argue this is a feature and not a bug, it does pose the issue that people might be overly optimistic about the security of the format.

Therefore removing it might be a better idea. This doesn't change any functionality since users can still trust the file by blindly passing `trusted=get_untrusted_types(...)`

cc @BenjaminBossan 

I also have to say, having typehints made the process a LOT easier here.

2024-06-06 13:44 UTC, BenjaminBossan commented
> We got a CVE report where an attacker can execute arbitrary code with `trusted=True`. While one can argue this is a feature and not a bug, it does pose the issue that people might be overly optimistic about the security of the format.

IMO this is a bit silly, with the same logic the whole pickle module would need to be removed. But I guess since there is a simple (albeit not really safer) solution, I'd be okay with the change. I'm wondering, however, if this should be deprecated?

> This doesn't change any functionality since users can still trust the file by blindly passing `trusted=get_untrusted_types(...)`

We could add a check that `__repr__` has been called at least once on the output of `get_untrusted_types` and at least 1 second per item has passed since. Just kidding of course, but yeah...

> I also have to say, having typehints made the process a LOT easier here.

Nice!

2024-06-06 13:48 UTC, adrinjalali commented
> I'm wondering, however, if this should be deprecated?

We used to have the hint that the API is really subject to change though. That's why I didn't deprecate. However, this has been used now for a while and pretty stable. So I removed the comment here and from now we can be even more conservative in changes.

2024-06-06 16:03 UTC, BenjaminBossan requested changes
The changes LGTM (though I still don't think they're really necessary).

I think mypy should pretty much make sure that the change was propagated completely through the code base. I still grepped through the code and found some instances that may need updates (see comments).

Apart from that, how about adding a paragraph to the docs that explicitly mentions that the `trusted=True` option was removed (and why using it was a bad idea anyway). Since this is a breaking change, making sure that users can quickly find a reference to this would be beneficial.

2024-06-06 16:03 UTC, BenjaminBossan commented on docs/changes.rst
> +  :pr:`422` by `Adrin Jalali`_.
Maybe add an explanation.

2024-06-10 14:11 UTC, adrinjalali reviewed
I think I addressed the comments @BenjaminBossan

2024-06-13 08:45 UTC, adrinjalali commented
@BenjaminBossan you okay with this now?

2024-06-13 09:54 UTC, BenjaminBossan approved these changes
Thanks for making the adjustments, this LGTM.

I have a nit about a type check, please take a look and decide if you want to fix it (you can merge no matter what).

While reviewing, I also stumbled upon the fact that `from typing import Sequence` is apparently deprecated:

https://docs.python.org/3/library/typing.html#typing.Sequence

Not sure if the tests should have caught that. Anyway, this can be addressed in a separate PR.

2024-06-13 10:20 UTC, adrinjalali commented
> While reviewing, I also stumbled upon the fact that from typing import Sequence is apparently deprecated:

Cool, I'll open a separate PR for that.

2024-06-13 10:49 UTC, merged

2024-06-27 07:15 UTC, judahrand commented
Could a release with this change be put out so that we can silence our CVE warning 😅

2024-07-03 14:48 UTC, adrinjalali commented
@judahrand yes, working on a numpy2 compatibility PR and will release with that one.

2024-07-03 16:05 UTC, adrinjalali commented
Release is out.